server:
  port: 8000

spring:
  kafka:
    producer:
      bootstrap-servers: 0.0.0.0:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery:
          timeout:
            ms: 10000
        linger:
          ms: 0
        request:
          timeout:
            ms:
              5000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

temperature:
  data:
    generation:
      interval: 300000